language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1

env:
  - JDK=oraclejdk8
  - JDK=oraclejdk7

before_script:
  - jdk_switcher use $JDK

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.1
      env: JDK=oraclejdk7
    - scala: 2.11.8
      env: JDK=oraclejdk8
    - scala: 2.10.6
      env: JDK=oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION pipeline

before_deploy:
  - mkdir -p $HOME/.bintray
  - openssl aes-256-cbc -K $encrypted_2a3b4d326ff7_key -iv $encrypted_2a3b4d326ff7_iv -in .credentials.enc -out $HOME/.bintray/.credentials -d

deploy:
  provider: script
  script: sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    branch: master
