language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1

env:
  - JDK=oraclejdk8
  - JDK=oraclejdk7

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.1
      env: JDK=oraclejdk7
    - scala: 2.11.8
      env: JDK=oraclejdk8
    - scala: 2.10.6
      env: JDK=oraclejdk8

before_script:
  - jdk_switcher use $JDK

script: sbt ++$TRAVIS_SCALA_VERSION test

before_deploy:
  - mkdir -p $HOME/.bintray $HOME/.ssh
  - openssl aes-256-cbc -K $encrypted_2a3b4d326ff7_key -iv $encrypted_2a3b4d326ff7_iv -in .travis/secrets.tgz.enc -out $HOME/secrets.tgz -d
  - tar -xzOf $HOME/secrets.tgz credentials > $HOME/.bintray/.credentials
  - tar -xzOf $HOME/secrets.tgz release-key > $HOME/.ssh/id_rsa
  - chmod 0600 $HOME/.ssh/id_rsa

deploy:
  - provider: script
    script: .travis/release.sh
    on:
      branch: master
      scala: 2.12.1
      condition: $(git log -n1 --format=format:"%an") != "Dwolla Bot"
  - provider: script
    script: sbt ++$TRAVIS_SCALA_VERSION publish
    on:
      tags: true
      condition: $(git log -n1 --format=format:"%an") == "Dwolla Bot"
