language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1

env:
  global:
    - secure: "anB13NhskkXdw57YNYqfVmvRJTcWSO3jwDTTmj2UhEw93AfJCs8qfh0MftUat2d5o6m3FnXPIiDhTglvqwi8EsbnJ9VfF50pIuKz6sX8YfZO3aQvRL9VY4eHH2AiyRuQ+1vTe8PgebD7sfAEWemTJ93TV1TkhTp3OMcOzNOhFDPJNfXaP6HpfaUA5l/lq/31t+vlJJIhBnUdosolejA2b81ii/HFkFlqjaV/k+QE80O6LqUn5eko3rdsnReGFMHItQvRRO9586Ta/gdW6TcdhfBjQfLHmiL8qpMVhkRzEnNLNRrsODJnOj04tNYWGDEQmeE/pZ/xL8++nb5hcvhgEflHuoGTuyrpdOHNw5SO6tI0Z2lRlQTHv2TPWtTh9SU0EEJObWOj3dxhEQ7jWNJrH4AA2gwTXXueL7twS7G5K2ZI2JZLtqk0Y+iMmup5/AJLrosFOCN/kLc2lQMyNHqdDN9IgVeTnLMfEf8/fLUwgln2pu4ikV5xabWABd914WJXYPFe7T9D99Y6pAxsehhZr6JQqUVsCHuJWAnGeOj08yGfisR7tJvo/b0jw70+DUjPiGZwMtVy7WXV8gMgMbk86FMowv0qcNHs0hKlojhwANkCFAvqB3Doqu1KT2h2I5XNM0KhqTvNkMUWc8DjiODAyvXDeT4hkZ+1Ka89VolyrZc="
  matrix:
    - JDK=oraclejdk8
    - JDK=oraclejdk7

matrix:
  # scala 2.12 requires java 8
  exclude:
    - scala: 2.12.1
      env: JDK=oraclejdk7
    - scala: 2.11.8
      env: JDK=oraclejdk8
    - scala: 2.10.6
      env: JDK=oraclejdk8

before_script:
  - jdk_switcher use $JDK

script: sbt ++$TRAVIS_SCALA_VERSION test

before_deploy:
  - mkdir -p $HOME/.bintray $HOME/.ssh
  - openssl aes-256-cbc -K $encrypted_2a3b4d326ff7_key -iv $encrypted_2a3b4d326ff7_iv -in .travis/secrets.tgz.enc -out $HOME/secrets.tgz -d
  - tar -xzOf $HOME/secrets.tgz credentials > $HOME/.bintray/.credentials
  - tar -xzOf $HOME/secrets.tgz release-key > $HOME/.ssh/id_rsa
  - chmod 0600 $HOME/.ssh/id_rsa

deploy:
  - provider: script
    script: .travis/release.sh
    on:
      branch: master
      scala: 2.12.1
      condition: $(git log -n1 --format=format:"%an") != "Dwolla Bot"
  - provider: script
    script: sbt ++$TRAVIS_SCALA_VERSION publish
    on:
      tags: true
      condition: $(git log -n1 --format=format:"%an") == "Dwolla Bot"
